[package]
name = "tilemapcache"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4.6.6", features = ["derive"] }
directories = "6.0.0"
open = "5.4.2"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
rusqlite = { version = "0.32", features = ["bundled"] }
strfmt = "0.2.5"
thiserror = "2.0.20"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
